import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import HeroSection from "@/components/heroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokémon Cards Search Engine</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Homepage}>
        <HeroSection />
      </div>
    </>
  );
}
